name: Allure Report

permissions:
  contents: write

on:
  push:
    branches: ["main"]

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Allure commandline
        uses: simple-elf/allure-commandline-action@v1.2
        with:
          version: 2.29.0

      - name: Restore
        run: dotnet restore

      - name: Test
        run: |
          if [ -d "./bin/Debug/net8.0/allure-results" ]; then rm -rf ./bin/Debug/net8.0/allure-results; fi
          dotnet test

      - name: Generate Allure Report
        run: |
          allure generate ./bin/Debug/net8.0/allure-results --clean -o ./allure-report

      - name: Publish to gh-pages
        run: |
          git fetch
          git checkout gh-pages || git checkout --orphan gh-pages
          rm -rf ./*
          cp -r ./allure-report/* .
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "Update Allure Report" || echo "No changes to commit"
          git push --force origin gh-pages
